### PR TITLE
Update to top of master and bug fix

### PR DESCRIPTION
**Pull request by RCL-Carl**
This PR contains a rebase on top of master and a bug fix for fixing false positives in the test.

### CODE REVIEW

**Comment by RCL-Carl** [comment]
FYI - I don't have authorization to merge this pull request - so I can test the process outlined in Issue #193 further than here.

**Comment by JdeH** [comment]
The team authorization settings were gone...
Maybe I hadn't properly saved them.
I've set them properly again.
You should be able to merge yourself now since you're in the subject owner team.
If not, let me know!

**Comment by JdeH** [comment]
Ha, it worked...

**Comment by JdeH** [comment]
So now whenever you think is best, make a PR from subject_autotester to master.
You can of course also accumulate some changes first, whatever you think is handy.

**Comment by JdeH** [comment]
Well, in principle the process seems to work.
I'll do some reading and experimenting with rebase now on a dummy account.
Indeed we should keep the graph as simple as possible.

This whole way of working takes some getting used to.

**Comment by RCL-Carl** [comment]
Yes - it does take some getting used to. The tree structure is quite complicated. Not necessarily a bad thing but definitely complex.

screen shot 2016-11-25 at 11 22 01 am

**Pull request merged**
