### PR TITLE
issubclass implementation

### PR DESCRIPTION
**Pull request by neriusmika**
Also fixed isinstance bug when checking primitives with `object` argument.

### CODE REVIEW

**Comment by JdeH** [comment]
Hi Nerius,

This will work, still two points of constructive criticism:

1. Function `isA` is in the global namespace, which I think we should avoid.
If `isA` has to be in the global namespace, could you use the name convention for system methods,
naming it `__isa__`. Developers will know that anything between `__ __` is reserved.

2. There's a lot of code duplication beween `isinstance` and `issubclass`.
I expect `isinstance` to be much smaller if it uses `issubclass`.
This few lines may not be a big deal, but accumulated over all built-in functions it will still amount to a significant amount of code, and guarding download size is very important as Transcrypt gets expanded over time.
A secundary advantage of this approach is that if `isinstance` achives its goal by calling `issubclass`, function `isA` can probably be local to `issubclass`, avoiding the name problem altogether.

**Comment by neriusmika** [comment]
Ok, I'll try to remove code duplication.

**Comment by neriusmika** [comment]
@JdeH, check the code now.

**Comment by JdeH** [comment]
Fine!

**Pull request merged**
