### PR TITLE
Property decorator setter implementation

### PR DESCRIPTION
**Pull request by neriusmika**
Implemented simple property decorator setter:

```python
@property
def my_property(self):
    return self.prop

@my_property.setter
def my_property(self, value):
    self.prop = value
```

### CODE REVIEW

**Comment by JdeH** [comment]
Beautiful!

**Comment by neriusmika** [comment]
Thank you. In my fork I pushed datetime module, but there still can be various untested cases. Used in my project for several months, so if you want, you can add it to transcrypt. If later someone find errors, I can fix them. Also for my own needs, I have encapsulated modules (like fabric in transcrypt) for velocity, redux, i18next, apollo client, leaflet, openlayers, snabbdom, stacktrace js, object-diff, watch, etc. If someone needs them, I can share them too.

**Comment by JdeH** [comment]
Given your concise coding style, if you've been using datetime for months, lets add it to the distribution. This indeed will allow others to give feedback.

About the encapsulated modules: I am quite sure some (or many) of them can be useful to others. If you're willing to share them, I wonder what's the best way to make them available. I'd like to take a peak in them to start with. Are they in your repo?

**Comment by JdeH** [comment]
I think the best way to add the datetime module and the datatime autotest to transcript is if you make it a pull request. In that way you'll be credited for it, which should be.

**Comment by neriusmika** [comment]
I will push them in repo, but now I think what is the best way to make them usable. It would be nice to put usage examples somewhere too. Actually I wrote my own framework with ideas from react, flask, etc. but it is not complete yet. Probably I need to make some application, because now I'm using it for company erp system and there is to much confidential information to make it available for public use. This is example of page rendering in my framework:

```python
import org.fuga.elementmaker as e
from application import apollo
from application.components.bootstrap.notification import notify
from application.helpers import icon_title
from application.layout.invoices.product_table import ProductTable
from application.layout.sidebar_page import SidebarPage
from application.model.graphql_queries import INVOICE, ALL_COMPANY_NAMES
from application.widgets import TextWidget, Form
from application.widgets.calendar import DateWidget
from com.i18next import i18n
from org.fuga.helpers import render_loading
from org.fuga.router import route, goback, navigate, url_for


class CustomerWidget(TextWidget):

    def __init__(self):
        super().__init__()
        self.onlink = None

    def render_control_readonly(self, container):
        # __pragma__('opov')
        if self.onlink:
            link = e.a(self.value, class_='form-control-static', href='javascript:;', onclick=self.onlink)
            container << e.div(e.p(link, class_='form-control-static'), style='width: 100%;')
        else:
            container << e.div(e.p(self.value, class_='form-control-static'), style='width: 100%;')
        # __pragma__('noopov')


@route('/invoices/view/<invoice_id>')
@apollo.query(INVOICE, ALL_COMPANY_NAMES)
class InvoiceView(SidebarPage):

    stylesheet = '''
.page-content {
  display: flex;
  flex-direction: column;
}

.fcl_form {
  overflow-y: auto;
  overflow-x: hidden;
}

.invoice-form {
  padding: 1rem 1rem 0 1rem;
  flex: 4 1 0;
}
    
.invoice-products {
  padding: 1rem 1rem 0 1rem;
  flex: 5 1 0;
}

.invoice-content {
  display: flex;
}

.btn-bar {
  flex: 0 0 auto;
  padding: 1rem;
}
'''

    # __pragma__('kwargs')
    def __init__(self, invoice_id):
        self._invoice_id = invoice_id

        self.number = TextWidget()
        self.docdate = DateWidget()
        self.customer = CustomerWidget()
        self.manager = TextWidget()
        self.tax = TextWidget()
        self.termdate = DateWidget()

        self.invoice_form = Form(readonly=True)
        self.invoice_form.add_widget(i18n.t('Number:'), self.number)
        self.invoice_form.add_widget(i18n.t('Document date:'), self.docdate)
        self.invoice_form.add_widget(i18n.t('Customer:'), self.customer)
        self.invoice_form.add_widget(i18n.t('VAT:'), self.tax)
        self.invoice_form.add_widget(i18n.t('Manager:'), self.manager)
        self.invoice_form.add_widget(i18n.t('Payment date:'), self.termdate)

        self.prod_table = ProductTable()
        self.prod_table.header = [
            {'title': i18n.t('Name'), 'colname': 'product_name'},
            {'title': i18n.t('Quantity'), 'colname': 'quantity', 'width': 65, 'type': 'int'},
            {'title': i18n.t('Price'), 'colname': 'price', 'width': 65, 'type': 'money4'},
            {'title': i18n.t('Total'), 'colname': 'total', 'width': 65, 'type': 'money4'},
        ]

        super().__init__()
        self.topmenu.menu_type = 'invoice_top'

    # __pragma__('nokwargs')

    def get_variables(self, query_name):
        if query_name == 'invoice':
            return {'id': self.invoice_id}

    @property
    def invoice_id(self):
        return self._invoice_id

    @invoice_id.setter
    def invoice_id(self, value):
        if self._invoice_id != value:
            self._invoice_id = value
            self.refetch('invoice')

    def clear_widgets(self):
        self.number.value = ''
        self.docdate.value = ''
        self.customer.value = ''
        self.customer.onlink = None
        self.tax.value = ''
        self.manager.value = ''
        self.termdate.value = ''
        self.prod_table.rows = []

    def fill_widgets(self):
        self.docdate.value = self.data.invoice.docdate
        self.number.value = self.data.invoice.number
        self.customer.value = self.data.invoice.customer['name']
        if self.data.invoice.customer.code and self.data.invoice.customer.code in [c.node.companyCode for c in
                                                                                   self.data.allCompanies.edges]:
            self.customer.onlink = lambda: self.oncustomer(self.data.invoice.customer.code)
        self.manager.value = self.data.invoice.managerName
        self.tax.value = '{} ({}%)'.format(self.data.invoice.tax['name'], self.data.invoice.tax['percents'])
        self.prod_table.vat_percents = self.data.invoice.tax['percents']
        self.termdate.value = self.data.invoice.termDate

        rows = []
        for prod in self.data.invoice.products.edges:
            prod = prod.node
            total = ((prod.price * 10000) * prod.altCount) / 10000

            row = {
                'product_name': {'data': prod.productName},
                'quantity': {'data': prod.altCount},
                'price': {'data': prod.price},
                'total': {'data': total},
            }
            rows.append(row)
        self.prod_table.rows = rows

    def ondata(self):
        if not self.data.invoice:
            notify('Invoice not found', 'Requested invoice not found, it may be deleted or wrong path specified',
                   'danger', 5000)
            goback(url_for('InvoiceList'))
        else:
            self.fill_widgets()
            self.update()

    def before_mount(self):
        super().before_mount()
        if not self.loading:
            self.fill_widgets()
        else:
            self.clear_widgets()

    def render_products(self):
        # __pragma__('opov')
        products = e.div(class_='invoice-products')
        products << e.h4(i18n.t('Products'))
        products << e.div(e.hr(style='margin-top: 0.5rem;'))
        products << self.prod_table
        # __pragma__('noopov')
        return products

    def render_form(self):
        # __pragma__('opov')
        form = e.div(class_='invoice-form')
        form << e.h4(i18n.t('Invoice'))
        form << e.div(e.hr(style='margin-top: 0.5rem;'))
        form << self.invoice_form
        # __pragma__('noopov')
        return form

    def render_buttons(self):
        # __pragma__('opov')
        buttons = e.div(class_='btn-bar btn-group')
        buttons << e.button(icon_title('fa fa-pencil-square-o', i18n.t('Edit')), class_='btn btn-primary', onclick=self.onedit)
        buttons << e.button(icon_title('fa fa-arrow-left', i18n.t('Back')), class_='btn btn-secondary', onclick=self.onback)
        # __pragma__('noopov')
        return buttons

    def render_content(self):
        # __pragma__('opov')
        content = e.div(self.render_form(), self.render_products(), class_='invoice-content')
        container = e.div(content, self.render_buttons(), class_='page-content')
        # __pragma__('noopov')

        if not self.loading:
            return container
        else:
            return render_loading(container)

    def onedit(self, event):
        url = url_for('InvoiceEditor', invoice_id=self.invoice_id)
        navigate(url)

    def onback(self, event):
        if not event.detail or event.detail == 1:  # prevent dblclick
            goback(url_for('InvoiceList'))

    def oncustomer(self, code):
        company_id = None
        for c in self.data.allCompanies.edges:
            if c.node.companyCode == code:
                company_id = c.node.id
                break
        if not company_id:
            raise __new__(Error('Company not found'))
        url = url_for('CompanyView', company_id=company_id)
        navigate(url)
```

Actually I want to make this framework public, but just don't have enough time to complete some components, etc. It supports routing similar to flask, inheritable stylesheets for components, virtual dom rendering with snabbdom, plugins in flask blueprints style, components to handle qraphql requests, etc. The best way I think would be to make some application like a chess or something and release those modules with examples.

**Comment by neriusmika** [comment]
@JdeH how are tests executed on the server? Is `transcrypt -r autotest.py` always run with `transcrypt -b -c -da autotest.py`? Because in datetime tests, there is a function `now` and I'm checking hours, thus, if there is at least a hour difference between those calls, the test will fail. Or it's better to remove such functions from the test?

**Comment by JdeH** [comment]
@neriusmika 

Some preliminary thougts about publicizing Transcrypt packages in general. I think that the primary means of distribution should be PyPi / pip install, or whatever successors the Python community comes up with. This is the road I took with Numscrypt (however tiny). In this way also packages can be publicized that run both under CPython and under Transcrypt, which is quite possible in some cases.

Furthermore, thinking ahead, probably not everything should be part of the Transcrypt repo. Fabric was just an example, and maybe adding some more examples would be useful. But in general putting everything there creates an unnecessary bottleneck. What I'd like best is total freedom for anyone willing to contribute packages that run under Transcrypt. So a separate repo, a separate PyPi package etc.. 

Standard packages like datetime should in my view be part of the distro, encapsulations of JS should in principle be separate PyPi packages, having a.o. the keyword Transcrypt, to be findable on PyPi or its successor. On www.transcrypt.org there should be a list of Transcrypt-compatible packages with a short description, a screenshot if applicable and hyperlinks to the PyPi package, the github repo, an eventual homepage and the documentation c.q. examples.

Note that this isn't in any way carved in stone. It's just my ideas, criticism and improvements welcome! This is beginning to become important just now, and there's still a lot of liberty to set a sensible course.

About the autotests: I've only set up the local system, which was then improved by @RCL-Carl. The continuous integration was set up by @AXGKl  , and I am not well informed with respect to the details. I try to concentrate upon Transcrypt itself to use my time as effectively as possible to keep the core OK. (And I work on NumScrypt since physics and maths is my professional working area). Before I push anything myself I always run the complete shipment test on Windows. At a new version I also run it on Linux. The CI test harness always performs `transcrypt -b -c -da autotest.py` and `transcrypt -b -c -da -r autotest.py`, along with other autotests, e.g. for the time module, which is separate. So there will be no large time difference if they're both done in the same timezone. In short, I don't expect things like `now` to cause trouble if small timedifferences are somehow neglected in the output (which would require some clever trick that I only have a vague idea about).

**Pull request merged**
