### PR TITLE
[WIP] Add unicodedata.normalize()

### PR DESCRIPTION
**Pull request by eddieantonio**
Let me know if there's a way I can add automated tests for this module!

Here's a simple test for this function:

```python
from unicodedata import normalize

# '\u00e8' == 'é'
# '\u0301' == 'e' + '\N{COMBINING ACUTE ACCENT}'
assert normalize('NFC', '\u00e9') == normalize('NFC', 'e\u0301'))
```

Addresses #547

### CODE REVIEW

**Comment by eddieantonio** [comment]
I'll whip up an autotest before this should be merged. Please let me know of any other things I should be aware of before this should be merged.

**Comment by JdeH** [comment]
Thanks for this speedy contribution!

Currently Travis CI isn't up to par with Transcrypt. This will be a while, since the one who made the CI work currently isn't available, and I'm not exactly a Travis expert...

But you can run the autotests off-line. To add an autotest for this module, add a testlet to _../Transcrypt/transcrypt/development/automated_tests/transcrypt_. Also at an import and an autotester.run call to _autotest.py_. The principle of the autotest system is described at:

http://www.transcrypt.org/docs/html/autotesting_transcrypt.html

Due to the transition of TS 3.6 to TS 3.7 the documentation on autotesting may still lag back on some points. If so let me know so it can be updated. You should also be able to run the shipment test but it requires node.js' http-server to be installed (as the Python http server has some problems).

**Comment by JdeH** [comment]
As you have contributed a new file, it can't break anything, so I'll already merge this.

**Comment by JdeH** [comment]
I don't think there are other things you should be aware of.
I hope this module will grow according to the needs of people.

**Comment by JdeH** [comment]
I've also manually drawn this into 3.7.
Are you still planning to add an autotest?

**Comment by eddieantonio** [comment]
Yes! I'll whip up a PR within the next two days.

**Comment by JdeH** [comment]
Thanks! And no hurry...

**Pull request merged**
