### PR TITLE
Ensure that ReST long_description displays well on Pypi

### PR DESCRIPTION
**Pull request by pombredanne**
* validate and update README.rst using @mgedmin restview --pypi-strict 

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by pombredanne** [comment]
Without this https://pypi.python.org/pypi/Transcrypt/ looks rather ugly and non-engaging!

**Comment by pombredanne** [comment]
You would need yo push a new version to see this of course

**Comment by JdeH** [comment]
Thanks,

I was wondering where the pictures had gone...

**Comment by pombredanne** [comment]
You are welcomed. I wish you would support Python 3.4 but this is an old dog (on some supported Ubuntu) and I can understand the appeal of 3.5!

**Comment by pombredanne** [comment]
FWIW:
`pip install restview` then `restview --pypi-strict` will show all errors. Thanks to @mgedmin

**Comment by JdeH** [comment]
Thanks, I never knew how to check the .RST's.
Sorry about 3.4, don't know exactly what the differences are.

**Comment by JdeH** [comment]
And the restview program works like a charm!

**Pull request merged**
