### PR TITLE
Add command-line flag for output directory

### PR DESCRIPTION
**Pull request by momothereal**
Adds a command-line flag (`-od` / `--outputdir`) to override the default output directory (`__target__`). Path is relative to the source directory, unless it is absolute (e.g. `/home/momo/...`)

### CODE REVIEW

**Comment by JdeH** [comment]
@momothereal 

Since on Windows the relpath function stalls if I use an abs path on another drive as -od command line option, I've solved it somewhat differently, by an explicit check.

I hope this covers the essence of what you propose.
It's currently in the dev_fall_2019 branch.
If it doesn't meet your needs, feel free to reopen.

Thanks for the contributrion!
Jacques

**Comment by momothereal** [comment]
Hey @JdeH. Sounds good. In the future, please consider marking the commit as ["co-authored"](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors) if you modify a contribution and use your own commit. Thanks :)

**Comment by momothereal** [comment]
@JdeH Hey, I really appreciate it! If you use `momothereal <momothereal.mc@gmail.com>` (the email I use for commits) it should work fine.

Thanks!

**Comment by JdeH** [comment]
Done it seems...

https://github.com/QQuick/Transcrypt/commit/38726e1bdd3a03cbc73db0daaea4ecae84e6e088

**Pull request closed without merging**
