### PR TITLE
Method decorators

### PR DESCRIPTION
**Pull request by neriusmika**
Here are the changes to allow method, classmethod, staticmethod decorators for Transcrypt. There are still too few tests, but as they do not change old behavior, I think we can merge them.

### CODE REVIEW

**Comment by neriusmika** [comment]
@JdeH as you better know compiler internals, can you look at the generated decorators after the class, sometimes they are missing semicolon at the end of line, sometimes they are duplicated. I can't find where and when they are added.

**Comment by neriusmika** [comment]
@JdeH something is wrong?

**Comment by JdeH** [comment]
Can't get Travis to build correctly.
Seems Python3.7 gives problems.
I am now trying to leave the 3.7 test out for the time being.

**Comment by JdeH** [comment]
All seems to work fine, except Python3.7, but that has nothing to do with your code.
I've been trying to locate the left out or doubled semicolons in the generated JS,
but haven't yet found them. Could you indicate in the code below where this occurs?

```
	__nest__ (
		__all__,
		'method_and_class_decorators', {
			__all__: {
				__inited__: false,
				__init__: function (__all__) {
					var run = function (autoTester) {
						var adecorator = __class__ ('adecorator', [object], {
							get __init__ () {return __get__ (this, function (self) {
								var kwargs = dict ();
								if (arguments.length) {
									var __ilastarg0__ = arguments.length - 1;
									if (arguments [__ilastarg0__] && arguments [__ilastarg0__].hasOwnProperty ("__kwargtrans__")) {
										var __allkwargs0__ = arguments [__ilastarg0__--];
										for (var __attrib0__ in __allkwargs0__) {
											switch (__attrib0__) {
												case 'self': var self = __allkwargs0__ [__attrib0__]; break;
												default: kwargs [__attrib0__] = __allkwargs0__ [__attrib0__];
											}
										}
										delete kwargs.__kwargtrans__;
									}
									var args = tuple ([].slice.apply (arguments).slice (1, __ilastarg0__ + 1));
								}
								else {
									var args = tuple ();
								}
								self.args = args;
								self.kwargs = kwargs;
							});},
							get __call__ () {return __get__ (this, function (self, func) {
								var wrapper = function () {
									var kwargs = dict ();
									if (arguments.length) {
										var __ilastarg0__ = arguments.length - 1;
										if (arguments [__ilastarg0__] && arguments [__ilastarg0__].hasOwnProperty ("__kwargtrans__")) {
											var __allkwargs0__ = arguments [__ilastarg0__--];
											for (var __attrib0__ in __allkwargs0__) {
												switch (__attrib0__) {
													default: kwargs [__attrib0__] = __allkwargs0__ [__attrib0__];
												}
											}
											delete kwargs.__kwargtrans__;
										}
										var args = tuple ([].slice.apply (arguments).slice (0, __ilastarg0__ + 1));
									}
									else {
										var args = tuple ();
									}
									var slf = args [0];
									var saved = dict ({});
									var __iterable0__ = self.kwargs.py_items ();
									for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
										var __left0__ = __iterable0__ [__index0__];
										var k = __left0__ [0];
										var v = __left0__ [1];
										if (hasattr (slf, k)) {
											saved [k] = getattr (slf, k);
											setattr (slf, k, v);
										}
									}
									var ret = func.apply (null, args.concat ([__kwargtrans__ (kwargs)]));
									var __iterable0__ = saved.py_items ();
									for (var __index0__ = 0; __index0__ < __iterable0__.length; __index0__++) {
										var __left0__ = __iterable0__ [__index0__];
										var k = __left0__ [0];
										var v = __left0__ [1];
										setattr (slf, k, v);
									}
									return ret;
								};
								return wrapper;
							});}
						});
						var method_decorator = function (prefix) {
							var inner_decorator = function (method) {
								var wrapper = function (self, py_name) {
									autoTester.check (py_name);
									return method (self, prefix + py_name);
								};
								return wrapper;
							};
							return inner_decorator;
						};
						var method_decorator2 = function (prefix) {
							var inner_decorator = function (method) {
								var wrapper = function (self, py_name) {
									autoTester.check (py_name);
									return method (self, prefix + py_name);
								};
								return wrapper;
							};
							return inner_decorator;
						};
						var multiplier = function (m) {
							var inner_decorator = function (method) {
								var wrapper = function (self, num) {
									autoTester.check (num);
									var n = method (self, num);
									return n * m;
								};
								return wrapper;
							};
							return inner_decorator;
						};
						var classmethod_decorator = function (method) {
							var wrapper = function (cls, a, b) {
								autoTester.check (cls.__name__, a, b);
								return method (cls, b, a);
							};
							return wrapper;
						};
						var class_decorator = function (prefix) {
							var wrapper = function (cls) {
								autoTester.check (prefix + cls.__name__);
								return cls;
							};
							return wrapper;
						};
						var MyClass = __class__ ('MyClass', [object], {
							InnerClass: __class__ ('InnerClass', [object], {
								__impl__mymethod: function (self, py_name) {
									autoTester.check (py_name);
								},
								get mymethod () {return __get__ (this, this.__impl__mymethod);},
								__impl__myclassmethod: function (cls, a, b) {
									autoTester.check (cls.__name__, a, b);
									return a + b;
								},
								get myclassmethod () {return __getcm__ (this, this.__impl__myclassmethod);},
								get mystaticmethod () {return function (a, b) {
									autoTester.check (a, b);
									return a + b;
								}}
							}),
							get __init__ () {return __get__ (this, function (self) {
								self.greetings = 'Hello';
							});},
							__impl__get_greetings: function (self) {
								return self.greetings;
							},
							get get_greetings () {return __get__ (this, this.__impl__get_greetings);},
							__impl__mymethod: function (self, py_name) {
								autoTester.check (py_name);
							},
							get mymethod () {return __get__ (this, this.__impl__mymethod);},
							__impl__number: function (self, num) {
								return num;
							},
							get number () {return __get__ (this, this.__impl__number);},
							get myclassmethod () {return __getcm__ (this, function (cls, a, b) {
								autoTester.check (cls.__name__, a, b);
								return a + b;
							});},
							get mystaticmethod () {return function (a, b) {
								autoTester.check (a + b);
								return a + b;
							}},
							get run () {return __get__ (this, function (self) {
								var inner_obj = self.InnerClass ();
								inner_obj.mymethod ('Dog');
								var result1 = inner_obj.myclassmethod ('param1', 'param2');
								var result2 = self.InnerClass.myclassmethod ('param1', 'param2');
								autoTester.check (result1 == result2);
								var result1 = inner_obj.mystaticmethod ('param1', 'param2');
								var result2 = self.InnerClass.mystaticmethod ('param1', 'param2');
								autoTester.check (result1 == result2);
							});}
						})
						MyClass.InnerClass.__impl__mymethod = method_decorator2 ('inner_second_') (MyClass.InnerClass.__impl__mymethod);
						MyClass.InnerClass.__impl__mymethod = method_decorator ('inner_first_') (MyClass.InnerClass.__impl__mymethod);
						MyClass.InnerClass.__impl__myclassmethod = classmethod_decorator (MyClass.InnerClass.__impl__myclassmethod);
						MyClass.InnerClass = class_decorator ('inner_') (MyClass.InnerClass);
						MyClass.__impl__get_greetings = __call__ (__call__ (adecorator, null, __kwargtrans__ ({greetings: 'Goodbye'})), null, MyClass.__impl__get_greetings);
						MyClass.__impl__mymethod = method_decorator2 ('second_') (MyClass.__impl__mymethod);
						MyClass.__impl__mymethod = method_decorator ('first_') (MyClass.__impl__mymethod);
						MyClass.__impl__number = multiplier (5) (MyClass.__impl__number);
						var MyClass = class_decorator ('outer_') (MyClass);
						var myobj = MyClass ();
						myobj.mymethod ('Cat');
						autoTester.check (myobj.greetings);
						autoTester.check (myobj.get_greetings ());
						var result1 = myobj.myclassmethod ('param1', 'param2');
						var result2 = MyClass.myclassmethod ('param1', 'param2');
						autoTester.check (result1 == result2);
						var result1 = myobj.mystaticmethod ('param1', 'param2');
						var result2 = MyClass.mystaticmethod ('param1', 'param2');
						autoTester.check (result1 == result2);
						autoTester.check (myobj.number (3));
						myobj.run ();
					};
					__pragma__ ('<all>')
						__all__.run = run;
					__pragma__ ('</all>')
				}
			}
		}
	);

```

**Comment by neriusmika** [comment]
In this code there is no such problem, but in other code sometimes I get double semicolons like this:
```javascript
var MyClass = class_decorator ('outer_') (MyClass);;
```
And there is no semicolon after initial class declaration.

**Comment by JdeH** [comment]
Could you give me the "Python" source code that this was generated from.
Then I can try to find out where it's generated.

**Comment by JdeH** [comment]
One thing I haven't tested is whether or not the new code interferes with line numbering of sourcemaps.
I will try that right away.

**Comment by JdeH** [comment]
Alright! Good that you're working on a datetime module. I often use that in CPython.

I've taken a look at the  behaviour of sourcemaps in combination with method- and class-decorators.
I'd say it's not worse than with the function decorators that were already there.
Decorators and sourcemaps in general are conceptually a difficult combination.
But the behaviour is consistent and bearable (one line off sometimes, but explainably so).
So I really think you did a great job here!

**Pull request merged**
