### PR TITLE
Master

### PR DESCRIPTION
**Pull request by AXGKl**
fixing time and adding isinstance compliancy

### CODE REVIEW

**Comment by AXGKl** [comment]
aargh, sooorry I screwed the formatting of transcrypt/development/automated_tests/transcrypt/classes/__init__.py :-(((

thought isinstance is not worth an own test, so added into yours but the tab -> spaces -> edit -> tabs workflow did fail somehow. Btw: You don't happen to have a vim config for your tab indented sources ?

I was replacing all tabs with four spaces then back but it failed.

PS: daylight saving should work but its crazy. ... (quote pydoc: DST is Daylight Saving Time, an adjustment of the timezone by (usually) one hour during part of the year. DST rules are magic (determined by local law) and can change from year to year. )

**Comment by AXGKl** [comment]
ok, think I fixed it. It was not an editor problem but a git problem, git ammend did not do what I thought ( as a mercurial guy git for me is still pita )

**Comment by AXGKl** [comment]
ok, conflict now with your builtins commit. Let me know if you want seperate PRs or you merge manually.

**Comment by JdeH** [comment]
Which files did you modify / create?

**Comment by AXGKl** [comment]
hi, created none, changed:
transcrypt/development/automated_tests/transcrypt/classes/__init__.py
transcrypt/development/automated_tests/time/testlet0.py
transcrypt/modules/time/__init__.py
transcrypt/development/automated_tests/hello/README.md
transcrypt/run_transcrypt (chmod)

and last but not least:

transcrypt/modules/org/transcrypt/__javascript__/__builtin__.mod.js

**Comment by JdeH** [comment]
Still behind your computer...
Glad I'm not the only one...

**Comment by AXGKl** [comment]
the interruption free part of the day just started ;-)

So I send you seperated PRs and we forget about this one, or can you handle?

**Comment by JdeH** [comment]
Connected google analytics to the site today.
Also uploaded a very simple movie of the mondrian turtle graphics to youtube.
And added some SEO info to the site.
For Python + Javascript on page one.
For Python + Browser on page three.

**Comment by AXGKl** [comment]
and... I am INFRONT of my computer. GRRRRR ;-)

**Comment by JdeH** [comment]
If it's not too much work, I'd like to try separate PR's.
Will handle them tomorrow, however, not enough concentration anymore, will make mistakes now.
Alright, so you're actually facing your screen then.
I use a mirror...

**Comment by AXGKl** [comment]
ok, I create 4 PRs

**Comment by AXGKl** [comment]
regarding youtube: This one really hit me yesterday, thats what the ruby guys built on top of their Transcypt - with which they have massive trouble with the native js access, since the syntax is so different, thats why yours does have actually so much more potential!

https://www.youtube.com/watch?v=KbFtIt7-ge8

**Comment by JdeH** [comment]
Nice video. He doesn't hesitate while talking and operating his computer. Rather hard to do (from experience). By the way, have you seen the conversation at issue #150? I'd like your (and dabo's) opinion on that, since the 'in' operator was made suitable for objects on your request. Should it stay like it is to cover your use cases, or being changed as proposed in #150? Original motivatioin was I believe that it's handy to have Python's 'in' behave like JS 'in' on (JS) objects, so also iterate through attribs that were inherited from prototype. What's your preference on this?

**Comment by AXGKl** [comment]
argh it does not work, when I sent one PR and then, after that send another this GitHub gui just appends the second to the first PR. 

I continue now and manually merge the builtins stuff from me , so that you don't have to merge. I have a lot of tests so I'm positive the isinstance improvements you can accept as is and merge all automatically. Or maybe with your permissions you can merge also the single commits of this new PR... sorry for that, have no Idea how I could create 4 isolated PRs w/o you accepting them intermediatelly.

**Comment by AXGKl** [comment]
I'll look into 150

**Comment by JdeH** [comment]
If you have done a manual merge, there will be no conflicts anymore, right?
So even if it's one PR, I could merge automatically, and then just do a QC/review diff?
In that case one PR is fine.

I will suspend any commits on __builtins__ for now to keep the target steady.

**Pull request closed without merging**
