### PR TITLE
New Demo: CycleJS

### PR DESCRIPTION
**Pull request by AXGKl**
Hi Jacques, this is just a set of new demos for a new js framework which many people consider very relevant.

### CODE REVIEW

**Comment by pierrejean-coudert** [comment]
@AXGKl Thanks for this really interesting demo 👍

**Comment by AXGKl** [comment]
merci Pierre-Jean.

Looking at stream processing code in python I ask myself if we need a PEP for dropping the need for backslashes when the next line begins with a dot. I begin to hate those \ them with a passion :-)

**Comment by JdeH** [comment]
You haven't been sitting still...
I'll pull it in blind trust and look at it later.
Still a bit scarce due to a new project.
Following the discussions, however.

**Comment by AXGKl** [comment]
> Still a bit scarce due to a new project.

*Not* sorry to say that you are not *that* much needed anymore - the thing just works :-) E.g. I'm using Transcrypt meanwhile totally naturally for anything I do in the browser. Modules and Marketing are imho at the highest prio but both not urgent.

**Comment by JdeH** [comment]
Hi Gunther

I've been playing around a bit with the CycleJS demo, not hindered by much knowledge of what I was doing. So probably I did something stupid.

I can get most of the demo's to work, and I especially like the slider demo.

But the bmi example I can't get going.
When I try to compile ite, I get the following report:

```
D:\activ_tosh\geatec\transcrypt\qquick\Transcrypt\transcrypt\__main__.py -n bmi.py 
Transcrypt (TM) Python to JavaScript Small Sane Subset Transpiler Version 3.6.3
Copyright (C) Geatec Engineering. License: Apache 2.0


Error in program bmi.py, module snabbdom, line 1: 
	Attempt to load module: snabbdom
	Can't find any of:
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/modules/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/modules/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/exe/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/exe/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/src/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/src/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/src_pyo/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/customers/marco_gotte/cardioWorkflowNT/src_pyo/pythonLibrary/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/__javascript__/snabbdom.mod.js
		D:/activ_tosh/geatec/transcrypt/qquick/Transcrypt/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/__javascript__/snabbdom.mod.js
		C:/Python35/python35.zip/__javascript__/snabbdom.mod.js
		C:/Python35/python35.zip/__javascript__/snabbdom.mod.js
		C:/Python35/DLLs/__javascript__/snabbdom.mod.js
		C:/Python35/DLLs/__javascript__/snabbdom.mod.js
		C:/Python35/lib/__javascript__/snabbdom.mod.js
		C:/Python35/lib/__javascript__/snabbdom.mod.js
		C:/Python35/__javascript__/snabbdom.mod.js
		C:/Python35/__javascript__/snabbdom.mod.js
		C:/Python35/lib/site-packages/__javascript__/snabbdom.mod.js
		C:/Python35/lib/site-packages/__javascript__/snabbdom.mod.js


Aborted
```

Do you have any idea what I'm doing wrong?

**Comment by AXGKl** [comment]
Oh - in deed, after a git reset --hard I get the error. Did not happen here because I had a compiled snabbdom.js in __javascript__ here, sorry. 
The components/snabbdom.py must be one directory higher then it seems to work again.

Or, better, like this:

```
--- a/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/components/labeled_slider.py
+++ b/transcrypt/demos/cyclejs_demo/component_demos/isolated_bmi_slider/components/labeled_slider.py
@@ -1,4 +1,4 @@
-from snabbdom import span, input, div
+from components.snabbdom import span, input, div
```


can you just commit it with any next commit ?

----------------------

Btw:

The need for snabbdom.py was the reason for my issue https://github.com/QQuick/Transcrypt/issues/251:

In original javascript he does sth like  `from DOM import "{div, h, span}"`  (forgot exact javascript build import syntax), then he uses `div`, `span`... in the module.

=> I wanted to replace that with sth like this:

```python
for tag in 'div', 'h', 'span':
      setattr(??, tag, getattr(DOM, tag))
```
and also have them avail in python directly, on module level. 

Did not manage to find a way, posted the issue, and helped me out with that `snabbdom.py` construction, allowing the module level `div`, `span` via python imports.

**Comment by JdeH** [comment]
About #251:  Looks quite doable, compact and usable to me. So it probably will be in soon.
About finding snabbdom, I'll adapt it.

**Comment by JdeH** [comment]
Fixed according to your suggestion.

**Pull request merged**
