### PR TITLE
3.5 3.6 3.7 on travis

### PR DESCRIPTION
**Pull request by AXGKl**
Tripping the tests now, for 3 python versions....

### CODE REVIEW

**Comment by AXGKl** [comment]
wait a second with merging... there was always a python3.5 on the machine as well, removing that....

**Comment by AXGKl** [comment]
# DON'T MERGE YET

(realizing the run_transcrypt is bound to python3.5... changing that currently)

**Comment by AXGKl** [comment]
uff, now its in.

Autodetecting the highest python version in the test_server and use this by default.

**Comment by AXGKl** [comment]
# Ready to merge.

**Comment by JdeH** [comment]
Great!
The switches should be equal.
So now, if I push or accept PR, which tests does it do on Travis?
Only Python 3.7? Or all three of them?

**Comment by AXGKl** [comment]
all three.

**Comment by AXGKl** [comment]
travis gui lists everything nicely.

**Comment by JdeH** [comment]
Seems I am not using Travis as effectively as I could.
Maybe I'll ask you for some help on becoming proficient with it.
First I'll try myself.

**Comment by AXGKl** [comment]
strange - I mean its just directly on the home page of them:

https://travis-ci.org/QQuick/Transcrypt/builds/179727754

screen shot 2016-11-29 at 16 43 08

**Comment by JdeH** [comment]
Hadn't realized these build jobs were all three triggered by the same pull request.
Thought you somehow explicitly triggered each one of those.

So 'Python 3.5' is, well, Python 3.5
'Python 3.'6 is the latest beta, probably
and 'Python nightly' is the bleeding edge of Python 3.7, right?

**Comment by AXGKl** [comment]
> But it's just the console log for each of these jobs, right?

right, when you click on the jobs you'll the console log. In the prepare output I run all `python[xy] --version`  so that we see whats really on the system installed. 

the test server then picks the highest available version but on your laptop you can control that by a CLI switch of the test_server.

**Comment by AXGKl** [comment]
> Hadn't realized these build jobs were all three triggered by the same pull request without human intervention.

builds are also triggered whenever you push, guess you knew that.

**Comment by JdeH** [comment]
Yes, I did.
I hadn't noticed the Python version in the console output though.
It's really all very practical.

**Pull request merged**
